[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@foundry-devops/=lib/foundry-devops/",
    "@openzeppelin=lib/openzeppelin-contracts",
    "@chainlink/contracts=lib/chainlink-brownie-contracts/contracts",
    "murky/=lib/murky/"
]

solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
# via_ir = true

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
    { access = "read-write", path = "./script/config" },
]

[invariant]
runs = 128
depth = 128
fail_on_revert = false